import joblib
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    accuracy_score,
    confusion_matrix
)

def build_ml_signals():
    print("Loading processed technical market data...")
    # Read the file generated by your step2 indicator engine script
    df = pd.read_csv('data/processed_market_data.csv')
    
    # 1. Feature Engineering (Generate predictive returns & volatility lags)
    df['Return_1h'] = df['Close'].pct_change(1)
    df['Return_5h'] = df['Close'].pct_change(5)
    df['Vol_5h'] = df['Close'].pct_change().rolling(5).std()
    
    # Target Setup: 1 if next hour's Close price rises higher than current close, else 0
    df['Target'] = (df['Close'].shift(-1) > df['Close']).astype(int)
    
    # Remove NaN values created during rolling calculation calculations
    df = df.dropna().copy()
    
    # Define active columns for feature space
    feature_cols = [
    'SMA_10',
    'SMA_50',
    'EMA_10',
    'EMA_20',
    'RSI_14',
    'MACD',
    'MACD_Signal',
    'ATR_14',
    'Return_1h',
    'Return_5h',
    'Vol_5h'
]   
    X = df[feature_cols]
    y = df['Target']
    
    # 2. Time-Series aware sequence train/test split (80% Train, 20% Out-of-Sample Test)
    split_idx = int(len(df) * 0.8)
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]
    
    print(f"Training Matrix Size: {len(X_train)} rows | Test Matrix Size: {len(X_test)} rows")
    
    # 3. Model Training Sequence
    model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
    model.fit(X_train, y_train)
    joblib.dump(
    model,
    "models/forex_random_forest.pkl"
    )

    print("Random Forest model saved successfully.")
    
    # 4. Out-of-Sample Evaluation Execution
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)

    print("\nFeature Importance")

    importance = pd.DataFrame({
    "Feature": feature_cols,
    "Importance": model.feature_importances_
    })

    importance = importance.sort_values(
    by="Importance",
    ascending=False
    )

    print(importance)
    
    print("\n==============================================")
    print(f"💰 MACHINE LEARNING OUT-OF-SAMPLE ACCURACY: {accuracy:.2%}")
    print("==============================================")
    print("\nClassification Metrics Report:")
    print(classification_report(y_test, predictions))

    print("\nConfusion Matrix")

    print(confusion_matrix(
    y_test,
    predictions
))
    
    # Save predictions out as an artifact for your Power BI dashboard model mapping
    df_test = df.iloc[split_idx:].copy()
    df_test["Signal"] = np.where(
    predictions == 1,
    "BUY",
    "SELL"
    )
    probability = model.predict_proba(X_test)

    df_test["Confidence"] = probability.max(axis=1)
    df_test.to_csv('data/ml_predictions.csv', index=False)
    print("--- SUCCESS: ML MODEL ENGINE LOGGED ---")
    print("Artifact saved to: 'data/ml_predictions.csv'")

if __name__ == "__main__":
    try:
        build_ml_signals()
    except Exception as e:
        print(f"An error occurred during machine learning runtime validation: {e}")